---
- src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse
#- src:
#  scm: git
#  version: "1.0"
#  name: lighthouse

#- src:
##  scm: git
#  version: "1.0"
#  name: vector
