---
- src: https://github.com/AlexeySetevoi/ansible-clickhouse.git ## пришлось заменить на https так как не клонировалось
  scm: git
  version: "1.13"
  name: clickhouse
- src: git@github.com:vasi4-dev/lighthouse-role.git
  #src: https://github.com/vasi4-dev/lighthouse-role.git # на случай, если понадобится
  scm: git
  version: "1.4"
  name: lighthouse

- src: git@github.com:vasi4-dev/vector-role.git
  #src: https://github.com/vasi4-dev/lighthouse-role.git # на случай, если понадобится
  scm: git
  version: "1.1"
  name: vector
